#!/usr/bin/env ruby 
# == Synopsis
# 
# Executable which delete files fitting criteria. 
# 
# The intended purpose is to delete backups older than a certain date,
# whilst keeping daily, weekly or monthly versions.
# 
# The executable does not itself create any backups, it is only 
# intended for cleaning up existing ones.
# 
# == Usage
# 
#   clean-files directory_path [options]
# 
# For help use: clean-files -h
# == Options
# 
#   -v, --verbose     Print name of files deleted
#   -d, --dry-run     Implies -v, only prints what files would have been deleted
#   -t, --threshold   Threshold date for when to start deleting files.
#                     No files newer than this date is deleted. 
#                  
#                     The argument is evaluated as Ruby, so it has to produce a valid 
#                     Ruby Time object. ActiveSupport time helpers can be used. 
#                     For example: 
#
#                     -t 10.days.ago or --threshold=2.months.ago
#                 
#   -h, --hourly      Keep hourly files
#   -d, --daily       Keep daily files
#   -w, --weekly      Keep weekly files
#   -m, --monthly     Keep monthly files
#   -y, --yearly      Keep yearly files
# 
#   -r, --recursive   Delete recursively into subdirectories
# 
# == Copyright
# 
# Copyright (c) 2009 AlphaSights Ltd. See LICENSE for details.
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
require 'lib/clean_files'

app = CleanFiles.new(ARGV)
app.run